### ISSUE TITLE
Exception using Arg<T>.Matches to constrain an expectation on an internal method

### ISSUE THREAD

**Issue by neontapir** [ayende/rhino-mocks#14]
I have a test:

    var controller = MockRepository.GeneratePartialMock<UserAdminController>(mockUserService, fakeContext); // mockUserService is a strict mock
    controller.Expect(x => x.Update(Arg<UserDetailModel>.Matches(y => !y.IsCreate))).Return(expectedResult);

If Update is public *or protected internal*, the test passes. If Update is internal, I get the following exception:

System.InvalidOperationException: When using Arg<T>, all arguments must be defined using Arg<T>.Is, Arg<T>.Text, Arg<T>.List, Arg<T>.Ref or Arg<T>.Out. 2 arguments expected, 1 have been defined.

**Comment by neontapir** [comment]
It's been over four years, I'm going to close this one.

**Comment by elbaloo** [comment]
@neontapir, project has been taken over by @meisinger, latest code is now at https://github.com/meisinger/rhino-mocks

**Comment by neontapir** [comment]
Thanks, @elbaloo
