### ISSUE TITLE
Expect throws InvalidCastException with Action

### ISSUE THREAD

**Issue by StijnVA** [ayende/rhino-mocks#21]
As followup with issue https://github.com/ayende/rhino-mocks/issues/6

The following code still throws an Exception
 
```
        public interface Foo
        {
            Action<int> Bar(); //Action<T>, T can be of any type
        }

        [TestMethod]
        public void TestMethod1()
        {
            var mock = MockRepository.GenerateMock<Foo>(); 
            mock.Expect(e => e.Bar()).Return(x => { }); //OK
            mock.Expect(e => e.Bar()).Return(x => { }); //Exception: System.InvalidCastException
        }

        [TestMethod]
        public void TestMethod2()
        {
            var mock = MockRepository.GenerateMock<Foo>();
            mock.Expect(e => e.Bar()).Repeat.Once().Return(x => { }); //OK
            mock.Expect(e => e.Bar()).Repeat.Once().Return(x => { }); //Exception: System.InvalidCastException
        }
```

**Comment by ayende** [comment]
What is the full error?

**Comment by StijnVA** [comment]
On my native .NET it throws

> exception:  **System.InvalidCastException**: Kan een object van het type **Castle.Proxies.ProxyDelegate_Action`1_1Proxy638de9cdbb2d45ee9c369527b7d6b0e8** niet converteren naar het type **System.Action`1[System.Int32]**

Wich roughly translate to

> exception:  System.InvalidCastException: Can not convert object of type Castle.Proxies.ProxyDelegate_Action`1_1Proxy638de9cdbb2d45ee9c369527b7d6b0e8 to type System.Action`1[System.Int32]

**Comment by ayende** [comment]
Thanks, I can confirm that this is a bug, and it has been fixed in the sources.

**Comment by abj27** [comment]
Are you planning on publishing those changes to nugget?

**Comment by ayende** [comment]
We aren't actively maintaining it, no

*Hibernating Rhinos Ltd  *

Oren Eini* l CEO l *Mobile: + 972-52-548-6969

Office: +972-4-622-7811 *l *Fax: +972-153-4-622-7811
