### ISSUE TITLE
Concurrency bug in MockRepository

### ISSUE THREAD

**Issue by Darxis69** [ayende/rhino-mocks#23]
I've triggered a bug in MockRepository class. The problem is with the static dictionary `generatorMap`, more precisely with following method (this is the only method that access this dictionary):

```
protected virtual ProxyGenerator GetProxyGenerator(Type type)
{
    if (!generatorMap.ContainsKey(type))
    {
        generatorMap[type] = new ProxyGenerator();
    }

    return generatorMap[type];
}
```

As tests are usually run in parallel, this can lead to a NullReferenceException in the GetProxyGenerator method when accessing/inserting into the dictionary (see http://stackoverflow.com/a/2195287/699850).

PR with Fix: #24

**Comment by ayende** [comment]
Thanks!
